# Generated by Django 4.0.4 on 2022-05-21 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=128)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wordmeanig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Wordmeanig', models.CharField(max_length=128)),
                ('priority', models.IntegerField()),
                ('word', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='web.word')),
            ],
        ),
    ]
